### ISSUE TITLE
A memory leak occurs during use, and the memory occupied by TsTreeNode cannot be automatically used.

### ISSUE THREAD

**Issue by msb8080** [bonede/tree-sitter-ng#15] opened 2024-04-19 08:38 UTC
A memory leak occurs during use, and the memory occupied by TSTree cannot be automatically used. TSTree's ptr and TSParser.ts_tree_delete are not exposed, and node memory cannot be manually released.

**Comment by msb8080** [comment] 2024-04-19 08:44
the current version is 0.22.2. 
I hope you can provide a method to manually release the memory occupied by the TSTree object, similar to the Tree#close method of the ai.serenade.treesitter project

**Comment by bonede** [comment] 2024-04-20 05:05
Hi,

`ts_tree_delete` will be called when TSTree object is garbage collected by JVM.

 In my opinion, it is a more natural way to do this in a garbage-collected language.

**Comment by chenzhf2019** [comment] 2024-04-22 01:40
I don't know if there is a problem with my use, in actual use I found that the virtual memory occupation will not be cleaned up, which will eventually cause the computer to crash.

**Comment by bonede** [comment] 2024-04-22 05:34
Hi,  could you paste a test case here? That will be helpful.

**Comment by chenzhf2019** [comment] 2024-04-22 08:27
@bonede  Hi，I simply created the TSTree by parsing the code in a loop and found that the virtual memory footprint kept increasing until the computer crashed. By the way, although the physical memory usage can be reduced, it needs to be manually invoked by the memory cleaning tool, rather than automatically cleared.
![image](https://github.com/bonede/tree-sitter-ng/assets/59008746/3724f3d2-ab90-45af-96a4-281d4802df27)
![image](https://github.com/bonede/tree-sitter-ng/assets/59008746/a49a1aee-dcf1-4edc-ae17-8d532feabfe0)

**Comment by chenzhf2019** [comment] 2024-04-22 09:22
As another issue, I found that treesitter's calculation of byte length is inconsistent with java's when the text contains emoji.
![image](https://github.com/bonede/tree-sitter-ng/assets/59008746/5da04cfc-9dc5-4884-a7fe-885c172f5e95)

**Comment by bonede** [comment] 2024-05-01 10:15
Hi, @chenzhf2019 

Thanks for reporting. The issue was fixed in 0.22.5a.

About the bytes length difference, Java use utf16 by default, tree-sitter use utf8 internal, this may cause the problem.

**Comment by msb8080** [comment] 2024-05-06 06:40
Is this issue also related to the usage of cleaner?

**Comment by bonede** [comment] 2024-05-12 08:18
@msb8080 yes

**Comment by bonede** [comment] 2024-05-12 08:21
@chenzhf2019  This issue is caused by how java dealing with UTF-8 strings. Java uses [Modified UTF-8](https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8) strings instead of normal UTF-8 strings.

Planned to fix this in the next release.

**Comment by marusic1514** [comment] 2024-05-21 17:12
I had the same issue with a bullet character, since it is not just one byte. Used this regex to cleanup the files before parsing: 
```
        val input = fileContents.replace("[^\\x00-\\x7F]".toRegex(), "")
```

**Comment by MRCCHHEN** [comment] 2024-06-04 07:34
> Hi,
> 
> `ts_tree_delete` will be called when TSTree object is garbage collected by JVM.
> 
> In my opinion, it is a more natural way to do this in a garbage-collected language.

This is not working; the server will still crash due to memory leaks when parsing a large batch of code.

**Comment by bonede** [comment] 2024-06-15 04:59
> > Hi,
> > `ts_tree_delete` will be called when TSTree object is garbage collected by JVM.
> > In my opinion, it is a more natural way to do this in a garbage-collected language.
> 
> This is not working; the server will still crash due to memory leaks when parsing a large batch of code.

Hi, 

Closing this thread. If it still occurs, please open new issue for this case.

**Closed by bonede** 2024-06-15 04:59 UTC
