### ISSUE TITLE
There is still an issue with parsing C++, the current version is 0.22.5

### ISSUE THREAD

**Issue by markkwu** [bonede/tree-sitter-ng#13] opened 2024-04-16 06:42 UTC
The error message is as follows：
---------------  T H R E A D  ---------------

Current thread (0x00007f78b8014000):  JavaThread "analyzeCodeChildThread-355959034229686272-1" [_thread_in_native, id=254, stack(0x00007f784aff6000,0x00007f784b0f7000)]

Stack: [0x00007f784aff6000,0x00007f784b0f7000],  sp=0x00007f784b0f3960,  free space=1014k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [x86_64-linux-gnu-tree-sitter-cpp.so+0x38ec09]  tree_sitter_cpp_external_scanner_deserialize+0x179
C  [x86_64-linux-gnu-tree-sitter.so+0x962f2]  ts_parser__external_scanner_deserialize+0x502
C  [x86_64-linux-gnu-tree-sitter.so+0x8b157]  ts_parser__lex+0x927
C  [x86_64-linux-gnu-tree-sitter.so+0x366ac]  ts_parser__advance+0x2cc
C  [x86_64-linux-gnu-tree-sitter.so+0x336f8]  ts_parser_parse+0x1e98
C  [x86_64-linux-gnu-tree-sitter.so+0x3d19e]  ts_parser_parse_string_encoding+0x6e
C  [x86_64-linux-gnu-tree-sitter.so+0x3d11e]  ts_parser_parse_string+0x2e
C  [x86_64-linux-gnu-tree-sitter.so+0xb555e]  Java_org_treesitter_TSParser_ts_1parser_1parse_1string+0x17e
j  org.treesitter.TSParser.ts_parser_parse_string(JJLjava/lang/String;)J+0
j  org.treesitter.TSParser.parseString(Lorg/treesitter/TSTree;Ljava/lang/String;)Lorg/treesitter/TSTree;+19
j  com.iflytek.ast.commons.treesitter.parser.AbstractParser.parse(Lcom/iflytek/ast/commons/treesitter/param/PrepareData;Lcom/google/common/collect/Table;)V+37
j  com.iflytek.ast.commons.treesitter.parser.AbstractParser.parseToTable(Lcom/iflytek/ast/commons/treesitter/param/PrepareData;)Lcom/google/common/collect/Table;+7
j  com.iflytek.ast.commons.treesitter.parser.AbstractParser.parse(Ljava/lang/String;)Ljava/util/Map;+14
j  com.aicode.codesearch.analyze.strategy.CppStrategy.codeAnalysis(Ljava/lang/String;)Ljava/util/List;+5
j  com.aicode.codesearch.analyze.strategy.AbstractCodeAnalyzeStrategy.commonCodeAnalysis(Ljava/lang/Long;Ljava/lang/String;)Ljava/util/List;+7
j  com.aicode.codesearch.analyze.CodeAnalyzeContext.lambda$processFile$0(Ljava/io/File;Lcom/aicode/codesearch/enums/LanguageEnum;Ljava/lang/String;Ljava/nio/file/Path;Ljava/lang/String;)V+54
j  com.aicode.codesearch.analyze.CodeAnalyzeContext$$Lambda$1031.run()V+24
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@11.0.5
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@11.0.5
j  java.lang.Thread.run()V+11 java.base@11.0.5
v  ~StubRoutines::call_stub
V  [libjvm.so+0x887449]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, Thread*)+0x3b9
V  [libjvm.so+0x8853fd]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, Thread*)+0x1ed
V  [libjvm.so+0x92fd4c]  thread_entry(JavaThread*, Thread*)+0x6c
V  [libjvm.so+0xdc6fed]  JavaThread::thread_main_inner()+0x21d
V  [libjvm.so+0xdc7397]  JavaThread::run()+0x377
V  [libjvm.so+0xc0b020]  thread_native_entry(Thread*)+0xf0

**Comment by markkwu** [comment] 2024-04-16 06:44
I noticed that you have updated the version of tree-sitter-cpp to 0.20.5, but there is no jar package for that version. I don't know if this is the reason.

**Comment by GenryEden** [comment] 2024-04-16 19:04
+1

**Comment by bonede** [comment] 2024-04-17 03:06
This is weird. Cpp and python parsers worked in [CI test ](https://github.com/bonede/tree-sitter-ng/blob/main/tree-sitter-cpp/src/test/java/org/treesitter/TreeSitterCppTest.java) and my Windows machine. 

I've uploaded cpp  0.20.5 to the Maven repository. Could you try again?

**Comment by GenryEden** [comment] 2024-04-17 17:55
yep, I still get the same error (tried with gradle clean)
more interesting is that I check disassembly of the x86_64-linux-gnu-tree-sitter-cpp.so at tree_sitter_cpp_external_scanner_deserialize+0x179 using objdump
and I see ud1 instruction there. 

I am not so strong in cpp or asssembly, but I can't find out if the instruction can be legally produced by compiler.

**Comment by markkwu** [comment] 2024-04-18 12:32
> This is weird. Cpp and python parsers worked in [CI test ](https://github.com/bonede/tree-sitter-ng/blob/main/tree-sitter-cpp/src/test/java/org/treesitter/TreeSitterCppTest.java) and my Windows machine.
> 
> I've uploaded cpp 0.20.5 to the Maven repository. Could you try again?


Yes, I tested it on the local Mac and there was no problem, but once it was on Linux, this issue would occur. I am running in Docker service, and my operating system version is Linux 7c1230dbda92 3.10.0-1160.95.1. el7. x86_64 # 1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux. The version of tree-sitter is 0.22.5, and the version of tree-sitter-cpp is 0.20.5. My test code is as follows:

#Include<iostream>
#Include<vector>

Using namespace std;

//Select sorting function
Void selectionSort (vector<int>&arr){
Int n=arr. size();
    
For (int i=0; i<n-1;++i){
Int minIndex=i;
For (int j=i+1; j<n;++j){
If (arr [j]<arr [minIndex]){
MinIndex=j;
}
}
        
//Swap the number at the current position with the decimal point
Int temp=arr [i];
Arr [i]=arr [minIndex];
Arr [minIndex]=temp;
}
}

Int main(){
Vector<int>arr={64, 25, 12, 22, 11};
    
Cout<"Original array:";
For (int num: arr){
Cout<<num<<";
}
Cout<<endl;
    
SelectionSort (arr);
    
Cout<"Sorted array:";
For (int num: arr){
Cout<<num<<";
}
Cout<<endl;
    
Return 0;
}


Actually, parsing any C++code will result in errors.

**Comment by GenryEden** [comment] 2024-04-18 13:52
I get it not for any c++ code, it throws error after some limit of size (or tokens count, not sure). 

For example, I get error for such code
```
void set_system(http_context& ctx, routes& r) {
    hm::get_metrics_config.set(r, [](const_req req) {
        std::vector<hm::metrics_config> res;
        res.resize(seastar::metrics::get_relabel_configs().size());
        size_t i = 0;
        for (auto&& r : seastar::metrics::get_relabel_configs()) {
            res[i].regex = r.expr.str();
            i++;
        }
        return res;
    });
}
```
but don't get it after deleting first line inside for loop.

**Comment by GenryEden** [comment] 2024-04-18 14:13
The problem is not in size or tokens count. One of found problems is that it doesn't like accessing fields or calling function of arrays elements (e.g. a[i].b).

For example
```

**Comment by GenryEden** [comment] 2024-04-18 14:20
The problem is not in size. It just have some syntax constructions that it doesn't like. 
Smallest of them is just `}`. Yeah, it's syntactically incorrect, but I don't think it's normal behavior to throw SIGILL for that case.

**Comment by GenryEden** [comment] 2024-04-18 21:46
idk what the problem is, but now I finally built it on linux (it didn't out of the box), and got the same problem, fixed by changing version of the cpp library to 0.22.0. 

Could you plz build the version and upload it to Maven repo?

**Comment by bonede** [comment] 2024-04-20 04:55
Hi,
CPP has been updated to 0.22.0. This should fixed the issue.

**Comment by bonede** [comment] 2024-04-22 01:18
Glad it works.  Close this now.

**Closed by bonede** 2024-04-22 01:18 UTC
